### ISSUE TITLE
Некоторые имена секций парсятся некорректно

### ISSUE THREAD

**Issue by KislyjKisel** [AziatkaVictor/ltx-support#13]
`ammo_5.7x28_ss190` парсит как `variable.other.constant.property` вместо обычного `entity.name.type.struct`, видимо из-за наличия точки. Просмотрел регуляркой - нашло ещё дефисы, которые не парсятся, например `gl_test_shell_ammo_vog-25`.

**Comment by AziatkaVictor** [comment]
Нашел причину, стояли строгие ограничения на тип символов внутри скобок. Сейчас же в регулярном выражении позволен любой смысл. Пока не уверен, повлияет ли это как-то на работу расширение (то есть, в плохую сторону), буду смотреть. Спасибо за баг репорт.
